### ISSUE TITLE
Game won't build

### ISSUE THREAD

**Issue by Bebersohl** [KevinJThomas/turn-based-adventure#32]
error output:

> ERROR in C:/Users/Brand/Documents/Projects/turn-based-adventure/src/app/play/playShared/p
> layDialog/play-dialog.component.ts (2,10): Module '"C:/Users/Brand/Documents/Projects/tur
> n-based-adventure/node_modules/@angular/material/material"' has no exported member 'MdDia
> logRef'.
> 
> ERROR in C:/Users/Brand/Documents/Projects/turn-based-adventure/src/app/play/playShared/h
> eroDialog/hero-dialog.component.ts (2,10): Module '"C:/Users/Brand/Documents/Projects/tur
> n-based-adventure/node_modules/@angular/material/material"' has no exported member 'MdDia
> logRef'.
> 
> ERROR in C:/Users/Brand/Documents/Projects/turn-based-adventure/src/app/play/game/levelUp
> Dialog/level-up-dialog.component.ts (2,10): Module '"C:/Users/Brand/Documents/Projects/tu
> rn-based-adventure/node_modules/@angular/material/material"' has no exported member 'MdDi
> alogRef'.
> 
> ERROR in C:/Users/Brand/Documents/Projects/turn-based-adventure/src/app/play/playShared/p
> lay.service.ts (2,10): Module '"C:/Users/Brand/Documents/Projects/turn-based-adventure/no
> de_modules/@angular/material/material"' has no exported member 'MdDialog'.
> 
> ERROR in C:/Users/Brand/Documents/Projects/turn-based-adventure/src/app/play/playShared/p
> lay.service.ts (2,20): Module '"C:/Users/Brand/Documents/Projects/turn-based-adventure/no
> de_modules/@angular/material/material"' has no exported member 'MdDialogRef'.
> 
> ERROR in C:/Users/Brand/Documents/Projects/turn-based-adventure/src/app/play/tutorial/tut
> orial.component.ts (2,10): Module '"C:/Users/Brand/Documents/Projects/turn-based-adventur
> e/node_modules/@angular/material/material"' has no exported member 'MdDialog'.
> 
> ERROR in C:/Users/Brand/Documents/Projects/turn-based-adventure/src/app/play/game/game.co
> mponent.ts (3,10): Module '"C:/Users/Brand/Documents/Projects/turn-based-adventure/node_m
> odules/@angular/material/material"' has no exported member 'MdDialog'.
> 
> ERROR in C:/Users/Brand/Documents/Projects/turn-based-adventure/src/app/play/play.module.
> ts (6,5): Module '"C:/Users/Brand/Documents/Projects/turn-based-adventure/node_modules/@a
> ngular/material/material"' has no exported member 'MdButtonModule'.
> 
> ERROR in C:/Users/Brand/Documents/Projects/turn-based-adventure/src/app/play/play.module.
> ts (7,5): Module '"C:/Users/Brand/Documents/Projects/turn-based-adventure/node_modules/@a
> ngular/material/material"' has no exported member 'MdInputModule'.
> 
> ERROR in C:/Users/Brand/Documents/Projects/turn-based-adventure/src/app/play/play.module.
> ts (8,5): Module '"C:/Users/Brand/Documents/Projects/turn-based-adventure/node_modules/@a
> ngular/material/material"' has no exported member 'MdCardModule'.
> 
> ERROR in C:/Users/Brand/Documents/Projects/turn-based-adventure/src/app/play/play.module.
> ts (9,5): Module '"C:/Users/Brand/Documents/Projects/turn-based-adventure/node_modules/@a
> ngular/material/material"' has no exported member 'MdToolbarModule'.
> 
> ERROR in C:/Users/Brand/Documents/Projects/turn-based-adventure/src/app/play/play.module.
> ts (10,5): Module '"C:/Users/Brand/Documents/Projects/turn-based-adventure/node_modules/@
> angular/material/material"' has no exported member 'MdSelectModule'.
> 
> ERROR in C:/Users/Brand/Documents/Projects/turn-based-adventure/src/app/play/play.module.
> ts (11,5): Module '"C:/Users/Brand/Documents/Projects/turn-based-adventure/node_modules/@
> angular/material/material"' has no exported member 'MdDialogModule'.
> 
> ERROR in C:/Users/Brand/Documents/Projects/turn-based-adventure/src/app/play/play.module.
> ts (12,5): Module '"C:/Users/Brand/Documents/Projects/turn-based-adventure/node_modules/@
> angular/material/material"' has no exported member 'MdListModule'.
> 
> ERROR in C:/Users/Brand/Documents/Projects/turn-based-adventure/src/app/play/play.module.
> ts (13,5): Module '"C:/Users/Brand/Documents/Projects/turn-based-adventure/node_modules/@
> angular/material/material"' has no exported member 'MdTooltipModule'.
> 
> ERROR in C:/Users/Brand/Documents/Projects/turn-based-adventure/src/app/play/play.module.
> ts (14,5): Module '"C:/Users/Brand/Documents/Projects/turn-based-adventure/node_modules/@
> angular/material/material"' has no exported member 'MdProgressSpinnerModule'.
> 
> ERROR in C:/Users/Brand/Documents/Projects/turn-based-adventure/src/app/play/play.module.
> ts (15,5): Module '"C:/Users/Brand/Documents/Projects/turn-based-adventure/node_modules/@
> angular/material/material"' has no exported member 'MdGridListModule'.
> 
> ERROR in C:/Users/Brand/Documents/Projects/turn-based-adventure/src/app/play/play.module.
> ts (16,5): Module '"C:/Users/Brand/Documents/Projects/turn-based-adventure/node_modules/@
> angular/material/material"' has no exported member 'MdProgressBarModule'.
> 
> ERROR in C:/Users/Brand/Documents/Projects/turn-based-adventure/src/app/app.module.ts (7,
> 3): Module '"C:/Users/Brand/Documents/Projects/turn-based-adventure/node_modules/@angular
> /material/material"' has no exported member 'MdButtonModule'.
> 
> ERROR in C:/Users/Brand/Documents/Projects/turn-based-adventure/src/app/app.module.ts (8,
> 3): Module '"C:/Users/Brand/Documents/Projects/turn-based-adventure/node_modules/@angular
> /material/material"' has no exported member 'MdInputModule'.
> 
> ERROR in C:/Users/Brand/Documents/Projects/turn-based-adventure/src/app/app.module.ts (9,
> 3): Module '"C:/Users/Brand/Documents/Projects/turn-based-adventure/node_modules/@angular
> /material/material"' has no exported member 'MdCardModule'.
> 
> ERROR in C:/Users/Brand/Documents/Projects/turn-based-adventure/src/app/app.module.ts (10
> ,3): Module '"C:/Users/Brand/Documents/Projects/turn-based-adventure/node_modules/@angula
> r/material/material"' has no exported member 'MdToolbarModule'.
> 
> ERROR in C:/Users/Brand/Documents/Projects/turn-based-adventure/src/app/app.module.ts (11
> ,3): Module '"C:/Users/Brand/Documents/Projects/turn-based-adventure/node_modules/@angula
> r/material/material"' has no exported member 'MdCheckboxModule'.
> 
> ERROR in C:/Users/Brand/Documents/Projects/turn-based-adventure/src/app/app.module.ts (12
> ,3): Module '"C:/Users/Brand/Documents/Projects/turn-based-adventure/node_modules/@angula
> r/material/material"' has no exported member 'MdListModule'.
> 
> ERROR in MdButtonModule is not an NgModule
> 
> ERROR in C:/Users/Brand/Documents/Projects/turn-based-adventure/src/app/app.module.ts (7,
> 3): Module '"C:/Users/Brand/Documents/Projects/turn-based-adventure/node_modules/@angular
> /material/material"' has no exported member 'MdButtonModule'.
> 
> ERROR in C:/Users/Brand/Documents/Projects/turn-based-adventure/src/app/app.module.ts (8,
> 3): Module '"C:/Users/Brand/Documents/Projects/turn-based-adventure/node_modules/@angular
> /material/material"' has no exported member 'MdInputModule'.
> 
> ERROR in C:/Users/Brand/Documents/Projects/turn-based-adventure/src/app/app.module.ts (9,
> 3): Module '"C:/Users/Brand/Documents/Projects/turn-based-adventure/node_modules/@angular
> /material/material"' has no exported member 'MdCardModule'.
> 
> ERROR in C:/Users/Brand/Documents/Projects/turn-based-adventure/src/app/app.module.ts (10
> ,3): Module '"C:/Users/Brand/Documents/Projects/turn-based-adventure/node_modules/@angula
> r/material/material"' has no exported member 'MdToolbarModule'.
> 
> ERROR in C:/Users/Brand/Documents/Projects/turn-based-adventure/src/app/app.module.ts (11
> ,3): Module '"C:/Users/Brand/Documents/Projects/turn-based-adventure/node_modules/@angula
> r/material/material"' has no exported member 'MdCheckboxModule'.
> 
> ERROR in C:/Users/Brand/Documents/Projects/turn-based-adventure/src/app/app.module.ts (12
> ,3): Module '"C:/Users/Brand/Documents/Projects/turn-based-adventure/node_modules/@angula
> r/material/material"' has no exported member 'MdListModule'.
> 
> ERROR in C:/Users/Brand/Documents/Projects/turn-based-adventure/src/app/play/play.module.
> ts (6,5): Module '"C:/Users/Brand/Documents/Projects/turn-based-adventure/node_modules/@a
> ngular/material/material"' has no exported member 'MdButtonModule'.
> 
> ERROR in C:/Users/Brand/Documents/Projects/turn-based-adventure/src/app/play/play.module.
> ts (7,5): Module '"C:/Users/Brand/Documents/Projects/turn-based-adventure/node_modules/@a
> ngular/material/material"' has no exported member 'MdInputModule'.
> 
> ERROR in C:/Users/Brand/Documents/Projects/turn-based-adventure/src/app/play/play.module.
> ts (8,5): Module '"C:/Users/Brand/Documents/Projects/turn-based-adventure/node_modules/@a
> ngular/material/material"' has no exported member 'MdCardModule'.
> 
> ERROR in C:/Users/Brand/Documents/Projects/turn-based-adventure/src/app/play/play.module.
> ts (9,5): Module '"C:/Users/Brand/Documents/Projects/turn-based-adventure/node_modules/@a
> ngular/material/material"' has no exported member 'MdToolbarModule'.
> 
> ERROR in C:/Users/Brand/Documents/Projects/turn-based-adventure/src/app/play/play.module.
> ts (10,5): Module '"C:/Users/Brand/Documents/Projects/turn-based-adventure/node_modules/@
> angular/material/material"' has no exported member 'MdSelectModule'.
> 
> ERROR in C:/Users/Brand/Documents/Projects/turn-based-adventure/src/app/play/play.module.
> ts (11,5): Module '"C:/Users/Brand/Documents/Projects/turn-based-adventure/node_modules/@
> angular/material/material"' has no exported member 'MdDialogModule'.
> 
> ERROR in C:/Users/Brand/Documents/Projects/turn-based-adventure/src/app/play/play.module.
> ts (12,5): Module '"C:/Users/Brand/Documents/Projects/turn-based-adventure/node_modules/@
> angular/material/material"' has no exported member 'MdListModule'.
> 
> ERROR in C:/Users/Brand/Documents/Projects/turn-based-adventure/src/app/play/play.module.
> ts (13,5): Module '"C:/Users/Brand/Documents/Projects/turn-based-adventure/node_modules/@
> angular/material/material"' has no exported member 'MdTooltipModule'.
> 
> ERROR in C:/Users/Brand/Documents/Projects/turn-based-adventure/src/app/play/play.module.
> ts (14,5): Module '"C:/Users/Brand/Documents/Projects/turn-based-adventure/node_modules/@
> angular/material/material"' has no exported member 'MdProgressSpinnerModule'.
> 
> ERROR in C:/Users/Brand/Documents/Projects/turn-based-adventure/src/app/play/play.module.
> ts (15,5): Module '"C:/Users/Brand/Documents/Projects/turn-based-adventure/node_modules/@
> angular/material/material"' has no exported member 'MdGridListModule'.
> 
> ERROR in C:/Users/Brand/Documents/Projects/turn-based-adventure/src/app/play/play.module.
> ts (16,5): Module '"C:/Users/Brand/Documents/Projects/turn-based-adventure/node_modules/@
> angular/material/material"' has no exported member 'MdProgressBarModule'.
> 
> ERROR in C:/Users/Brand/Documents/Projects/turn-based-adventure/src/app/play/tutorial/tut
> orial.component.ts (2,10): Module '"C:/Users/Brand/Documents/Projects/turn-based-adventur
> e/node_modules/@angular/material/material"' has no exported member 'MdDialog'.
> 
> ERROR in C:/Users/Brand/Documents/Projects/turn-based-adventure/src/app/play/game/game.co
> mponent.ts (3,10): Module '"C:/Users/Brand/Documents/Projects/turn-based-adventure/node_m
> odules/@angular/material/material"' has no exported member 'MdDialog'.
> 
> ERROR in C:/Users/Brand/Documents/Projects/turn-based-adventure/src/app/play/game/levelUp
> Dialog/level-up-dialog.component.ts (2,10): Module '"C:/Users/Brand/Documents/Projects/tu
> rn-based-adventure/node_modules/@angular/material/material"' has no exported member 'MdDi
> alogRef'.
> 
> ERROR in C:/Users/Brand/Documents/Projects/turn-based-adventure/src/app/play/playShared/p
> lay.service.ts (2,10): Module '"C:/Users/Brand/Documents/Projects/turn-based-adventure/no
> de_modules/@angular/material/material"' has no exported member 'MdDialog'.
> 
> ERROR in C:/Users/Brand/Documents/Projects/turn-based-adventure/src/app/play/playShared/p
> lay.service.ts (2,20): Module '"C:/Users/Brand/Documents/Projects/turn-based-adventure/no
> de_modules/@angular/material/material"' has no exported member 'MdDialogRef'.
> 
> ERROR in C:/Users/Brand/Documents/Projects/turn-based-adventure/src/app/play/playShared/p
> layDialog/play-dialog.component.ts (2,10): Module '"C:/Users/Brand/Documents/Projects/tur
> n-based-adventure/node_modules/@angular/material/material"' has no exported member 'MdDia
> logRef'.
> 
> ERROR in C:/Users/Brand/Documents/Projects/turn-based-adventure/src/app/play/playShared/h
> eroDialog/hero-dialog.component.ts (2,10): Module '"C:/Users/Brand/Documents/Projects/tur
> n-based-adventure/node_modules/@angular/material/material"' has no exported member 'MdDia
> logRef'.

**Comment by KevinJThomas** [comment]
This was caused by a new version of Angular Material changing their syntax. The code has been updated to match the new syntax.
